void main() {
  String ilce = 'İstanbul';
  String kita = 'Avrupa';
  String faks = 'faks';
  int posta_kodu = 34160;
  String insta_adresi = 'andactasdemir24';
  String calistigin_bolum = 'Yazılım';
  int urun_miktari = 5;
  String musteri_soyadi = 'Taşdemir';
  int odeme_miktari = 5;
  String dogum_tarihi = '03.05.2000';
  int borc = 5;
  String medeni_hal = 'bekar';
  String video_yorumu = 'güzel!';
  double odeme_saati = 17.05;
  double eft_miktari = 1700.00;
  int satilan_miktar = 1;
  String telefon_model = 'Oppo';
  String dergi_ad = 'uykusuz';
  String basim_tarihi = '01.01.2000';
  int zam_miktari = 50;
  int daire_sayisi = 4;
  double enlem = 15.00;
  double boylam = 15.00;
  String yemek_adi = 'Hamburger';
  double urun_fiyati = 59.99;
  String sirket = 'A holding';
  String video_adi = 'A videosu';
  double muzik_suresi = 04.56;
  int mekan_puani = 5;
  String resim_format = '.png';
  String renk = 'Mavi';
  String renk_kodu = '0xFF';
  String bilgisyar_model = 'Monster';
  int ekran_boyut = 64;
  int kullanim_suresi = 5;

  print('ilce: $ilce');
  print('kita: $kita');
  print('faks: $faks');
  print('posta_kodu: $posta_kodu');
  print('insta_adresi: $insta_adresi');
  print('calistigin_bolum: $calistigin_bolum');
  print('urun_miktari: $urun_miktari');
  print('musteri_soyadi: $musteri_soyadi');
  print('odeme_miktari: $odeme_miktari');
  print('dogum_tarihi: $dogum_tarihi');
  print('borc: $borc');
  print('medeni_hal: $medeni_hal');
  print('video_yorumu: $video_yorumu');
  print('odeme_saati: $odeme_saati');
  print('eft_miktari: $eft_miktari');
  print('satilan_miktar: $satilan_miktar');
  print('telefon_model: $telefon_model');
  print('dergi_ad: $dergi_ad');
  print('basim_tarihi: $basim_tarihi');
  print('zam_miktari: $zam_miktari');
  print('daire_sayisi: $daire_sayisi');
  print('enlem: $enlem');
  print('boylam: $boylam');
  print('yemek_adi: $yemek_adi');
  print('urun_fiyati: $urun_fiyati');
  print('sirket: $sirket');
  print('video_adi: $video_adi');
  print('muzik_suresi: $muzik_suresi');
  print('mekan_puani: $mekan_puani');
  print('resim_format: $resim_format');
  print('renk: $renk');
  print('renk_kodu: $renk_kodu');
  print('bilgisayar_model: $bilgisyar_model');
  print('ekran_boyut: $ekran_boyut');
  print('kullanim_suresi: $kullanim_suresi');
}
